sudo: required
services:
  - docker

  before_install:
    - docker build -t skgeorge/react-test -f ./client/Dockerfile.dev ./client

  script:
    - docker run skgeorge/react-test npm test -- --coverage

after_success:
  - docoker build -t skgeorge/multi-client ./client
  - docoker build -t skgeorge/multi-nginx ./nginx
  - docoker build -t skgeorge/multi-server ./server
  - docoker build -t skgeorge/multi-worker ./worker
  # log into the docker CLI 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # The these images and push them to  a dcker hub
  - docker push skgeorge/multi-client
  - docker push skgeorge/multi-nginx
  - docker push skgeorge/multi-server
  - docker push skgeorge/multi-worker
